# Use an official Node.js runtime as a base image
FROM node:19

# Set the working directory to /safal
WORKDIR /server

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install the app dependencies
RUN npm install

# Copy the TypeScript configuration and source files
COPY tsconfig.json ./
COPY . .



# Expose the port that your app will run on
EXPOSE ${PORT}

# Build the TypeScript code

RUN npm run build
# Command to run your application
CMD ["npm", "run", "start"]

#docker-compose up --build